### ISSUE TITLE
Not running with OpenModelica v1.21.0

### ISSUE THREAD

**Issue by SOFAgh** [MoSDH/MoSDH#2]
Unfortunately with the meaningless error message: Internal error Instantiation of MoSDH.Examples.ExampleGeothermalHeating failed with no error message.
I am using ModelicaStandardLibrary_v4.0.0
Any ideas what I could do?

**Comment by JFormhals** [comment]
Hi,
the model works fine for me with OM v1.21.0 on both my systems. I cannot reproduce the error. Try updating OM to the latest nightly build. I had troubles with certain versions of OM in the past as well.
You could try to get some help at OpenModelica directly https://github.com/OpenModelica/OpenModelica/issues
